config/routes.rb
Rails.application.routes.draw do
  resources :attractions
  resources :travelers do
    resources :trips
  end

  root 'static_pages#index'
  get '/signup', to: 'travelers#new'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#delete'
  post "/sessions/create", to: "sessions#create"
  get '/auth/:provider/callback', to: 'sessions#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_and_belongs_to_many :trips
  has_many :travelers, through: :trips

  validates :name, :location, :hours, presence: true
end

app/models/traveler.rb
class Traveler < ApplicationRecord
  has_secure_password
  has_many :trips
  has_many :attractions, through: :trips

  validates :name, :email, presence: true
  validates :email, uniqueness: {case_sensitive: false}
end

app/models/trip.rb
require 'pry'

class Trip < ApplicationRecord
  belongs_to :traveler
  has_and_belongs_to_many :attractions
  accepts_nested_attributes_for :attractions

  validates :name, :traveler_id, presence: true

  def self.trips?
    if self.all == []
      false
    end
  end

  def self.upcoming_trips
    @upcoming_trips = Trip.where("start_date < ?",90.days.from_now)
  end

end

#belongs_to traveler
#attraction has_many trips
#trip has_many attractions
#trip_attractions

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    session[:traveler_id] == @traveler.id
  end

  def set_user
      @traveler = Traveler.find(params[:id])
  end

end

app/controllers/attractions_controller.rb
require 'pry'
class AttractionsController < ApplicationController
before_action :set_traveler

  def new
    @attraction = Attraction.new
    render :layout => false
  end

  def create
    @attraction = Attraction.new(attraction_params)
    if @attraction.save
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @attraction}
      end
    else
      render :new
    end
  end

  def show
    @attraction = Attraction.find_by_id(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @attraction}
    end
  end

  def index
    @attractions = Attraction.all
  end

  def edit
    @attraction = Attraction.find_by_id(params[:id])
  end

  def update
    @attraction = Attraction.find(params[:id])
    @attraction.update(attraction_params)
    redirect_to attraction_path(@attraction)
  end

  def destroy
    @attraction = Attraction.find_by_id(params[:id])
    @attraction.delete
    redirect_to attractions_path
  end

  private

  def attraction_params
    params.require(:attraction).permit(
      :name,
      :location,
      :hours,
      :price,
    )
  end

  def set_traveler
    @traveler = Traveler.find_by_id(session[:traveler_id])
  end
end

app/controllers/sessions_controller.rb
require 'pry'

class SessionsController < ApplicationController

  def new
    @traveler = Traveler.new
  end

  def create
    if auth_hash =  request.env['omniauth.auth']
      @traveler = Traveler.find_or_create_by(:id => auth_hash['uid']) do |t|
        binding.pry
        t.name = auth_hash["info"]["nickname"],
        t.email = auth_hash["info"]["email"],
        t.password = SecureRandom.hex
      end
        session[:traveler_id] = @traveler.id
        redirect_to traveler_path(@traveler)
    else
      @traveler = Traveler.find_by(name: params[:traveler][:name])
      if @traveler && @traveler.authenticate(params[:traveler][:password])
        session[:traveler_id] = @traveler.id
        redirect_to traveler_path(@traveler)
      else
        render :new
      end
    end
  end

  def delete
    session.clear
    redirect_to '/'
  end

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/static_pages_controller.rb
require 'pry'

class StaticPagesController < ApplicationController

  def index
    if session[:traveler_id]
      @traveler = Traveler.find_by_id(session[:traveler_id])
      if @traveler
        redirect_to traveler_path(@traveler)
      else
        :index
      end
    end
  end

end

app/controllers/travelers_controller.rb
require 'pry'
class TravelersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_traveler, only: [:show, :index]


  def show
    render :show
  end

  def index
    @travelers = Traveler.all
    render :index
  end

  # def trips_index
  #   @traveler = Traveler.find(params[:id])
  #   @trips = @traveler.trips
  #   render json: @trips, status: 201
  # end

  # def trip
  #   @traveler = Traveler.find(params[:id])
  #   @trip = Trip.find(params[:trip_id])
  #   render template: 'trips/show'
  # end

  def new
    @traveler = Traveler.new
  end

  def create
    @traveler = Traveler.new(traveler_params)
    if @traveler.save
      session[:traveler_id] = @traveler.id
      redirect_to @traveler
    else
      render :new
    end
  end

  private

  def traveler_params
    params.require(:traveler).permit(
      :name,
      :email,
      :budget,
      :password,
      :nationality,
      :interests
    )
  end

  def require_login
    return head(:forbidden) unless session.include? :traveler_id
  end

  def set_traveler
        @traveler = Traveler.find_by_id(session[:traveler_id])
  end

end

app/controllers/trips_controller.rb
require 'pry'
class TripsController < ApplicationController
  before_action :set_traveler, only: [:new, :create, :show, :index, :edit, :update, :destroy]

  def new
    @trip = Trip.new(traveler_id: params[:traveler_id])
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to traveler_trips_path(@traveler)
    else
      render :new
    end
  end

  def index
    if params[:traveler_id].to_f == session[:traveler_id]
      @trips = Traveler.find_by_id(params[:traveler_id]).trips
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @trips}
      end
    else
      render :new
    end
  end

  # // DELETE /travelers/:traveler_id/trips/:id(.:format)
  def destroy
    @traveler = Traveler.find(params[:traveler_id])
    @trip = @traveler.trips.find(params[:id])
    @trip.destroy
    redirect_to traveler_path(@traveler)
  end

  def show
    @trip = Trip.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @trip}
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    if @trip.save
      redirect_to traveler_trips_path(@traveler)
    else
      render :edit
    end
  end

  def attraction_attributes=(attraction_attributes)
    attraction_attributes.values.each do |attraction_attribute|
      attraction = Attraction.find_or_create_by(attraction_attribute)
      self.attractions << attraction
    end
  end


  private

  def trip_params
    params.require(:trip).permit(
      :name,
      :start_date,
      :end_date,
      :traveler_id,
      attraction_ids:[],
    )
  end

  def set_traveler
    @traveler = Traveler.find_by_id(session[:traveler_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/travellers_helper.rb
module TravellersHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/attractions/edit.html.erb
<div class="row">
  <div class="column">
    <div class="info-text">
      <h1> Edit <%=@attraction.name%></h1> </br>
    </div>
  </div>
  <div class="column">
    <div class="form">
      <%= form_for @attraction, url: attraction_path(@attraction), :method => :patch  do |f| %>
      <% if @attraction.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@attraction.errors.count, "error") %>
            prohibited this post from being saved:
          <ul>
          <% @attraction.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
          </h3>
        </div>
      <% end %>
          Name: <%=f.text_field :name %></br>
          Location: <%=f.text_field :location %></br>
          Hours: <%=f.text_field :hours %></br>
          Price: <%=f.text_field :price %></br>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/attractions/index.html.erb

<div class="row" >
  <div class="column">
    <div class="info-text">
      <h1> All Attractions</h1>
    </div>
  </div>
  <div class="column" id="attractions">
    <div class="form">
      <%@attractions.each do |a|%>
        <%=link_to a.name, attraction_path(a)%></br>
      <%end%>
      <br> <%if session.include? :traveler_id%>
        <a href="<%=new_attraction_path%>" class="button">Create New Attraction</a>
      <%end%>
    </div>
  </div>
<div>

app/views/attractions/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'attractions' %>
	<title>New Attraction</title>
</head>

  <body>

   <div class="row">
    <div class="column">
      <div class="info-text">
        <h1> Create New Attraction</h1>
      </div>
    </div>
    <div class="column">
      <div class="form">
        <%=  form_for @attraction, url: attractions_path do |f| %>
        <% if @attraction.errors.any? %>
          <div id="error_explanation">
            <h3>
              <%= pluralize(@attraction.errors.count, "error") %>
              prohibited this post from being saved:
            <ul>
            <% @attraction.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
            </h3>
          </div>
        <% end %>
            Name: <%=f.text_field :name %></br>
            Location: <%=f.text_field :location %></br>
            Hours: <%=f.text_field :hours %></br>
            Price: <%=f.text_field :price %></br>
          <%= f.submit %>
        <% end %>

      </div>
    </div>
  </div>

  </body>
</html>

app/views/attractions/show.html.erb
<div class="row">
  <div class="column">
    <div class="info-text">
      <h1 id="attractionName"><%=@attraction.name%></h1>
      <!-- <h1> <%=@attraction.name%></h1> </br> -->
    </div>
  </div>
  <div class="column" id="attractions">
    <div class="form" id="attractionResults">
      <h2 id="attractionLocation">Location: <p><%=@attraction.location%></p></h2>
      <h2 id="attractionHours">Hours: <p><%=@attraction.hours%></p></h2>
      <h2 id="attractionPrice">Price: <p><%=@attraction.price%></p></h2>
      <div><%= link_to "Edit Attraction", edit_attraction_path(@attraction) %></div>
      <div><a href="#" class="js-next" data-id="<%=@attraction.id%>">Next Attraction</a></div>
      <%= link_to "Delete Attraction", attraction_path(@attraction), :method => :delete %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelerTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Markazi+Text" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <!-- <%= javascript_include_tag 'attractions' %> -->
    <!-- <%= javascript_include_tag 'trips' %> -->
    </head>
  </head>

  <body>
    <div class="topnav">
        <%if session[:traveler_id] && @traveler %>
          <a href="/logout">Logout</a>
          <a href="<%=attractions_path%>">Attractions</a>
          <a href="<%=traveler_trips_path(@traveler)%>">Trips</a>
          <a href="<%=traveler_path(@traveler)%>">Profile</a>
        <%end%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.erb

<div>
  <h1>Welcome to Traveler Tracker</h1>
  <p> Build, View and Share travel plans with friends and loved ones. </p>
</div>

<div class="first">
  <a href="/login" class="button">Log In</a>
</div>

<div class="second">
  <a href="/signup" class="button">Sign Up</a>
</div>

app/views/travelers/_form.html.erb
<%=form_for @traveler do |f|%>
  <%=f.label :name%><br />
  <%=f.text_field :name%> <br />
  <%=f.label :email%><br />
  <%=f.text_field :email%> <br />
  <%=f.label :password%><br />
  <%=f.text_field :password%> <br />
  <%=f.label :budget%><br />
  <%=f.text_field :budget%> <br />
  <%=f.label :nationality%><br />
  <%=f.text_field :nationality%> <br />
  <%=f.label :interests%><br />
  <%=f.text_field :interests%> <br />
  <%=f.submit id: 'Start Adventure'%><br />
<%end%>

app/views/travelers/index.html.erb
<div class="row" >
  <div class="column">
    <div class="info-text">
      <h1> See who else traveling!</h1> </br>
    </div>
  </div>
  <div class="column">
    <div class="form">
      <%@travelers.each do |t|%>
        <%=t.name%> </br>
      <%end%>
    </div>
  </div>

app/views/travelers/new.html.erb
<div class="row" >
  <div class="column">
    <div class="info-text">
      <h1> Welcome Traveler </br>
      Please Sign Up</h1> </br>
    </div>
  </div>
  <div class="column">
    <div class="form">
      <%= render 'form' %>
      <% if @traveler.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@traveler.errors.count, "error") %>
            prohibited this post from being saved:
          </h2>

          <ul>
          <% @traveler.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
<div>

app/views/travelers/show.html.erb
<div class="row">
  <div class="column">
    <div class="info-text">
      <h1> Welcome <%=@traveler.name%> </h1> </br>
      <br><h2> Additional Info </h2></br>
      <h2>Budget: $<%=@traveler.budget%></h2></br>
      <h2>Nationality: <%=@traveler.nationality%></h2></br>
      <h2>Interests: <%=@traveler.interests%></h2></br>
    </div>
 </div>
 <div class="column">
   <div class="form">
      <h2> Upcoming Trips </h2>
        <% if @traveler.trips%>
          <%@traveler.trips.upcoming_trips.each do |trip|%>
            <p><%= link_to trip.name, traveler_trip_path(@traveler, trip)%> </br></p>
          <%end%>
        <%else%>
          <p> You have no upcoming trips </p>
        <%end%>

      <a href="<%= new_traveler_trip_path(@traveler)%>" class="button">Create New Trip</a>
      <a id="indexTrips" href="#" data-id="<%=@traveler.id%>" class="button">View All Trips</a>
    </div>
  </div>
</div>

app/views/trips/_form.html.erb
<%= form_for @trip, url: traveler_trips_path do |f| %>
<% if @trip.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= pluralize(@trip.errors.count, "error") %>
      prohibited this post from being saved:
    <ul>
    <% @trip.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </h3>
  </div>
<% end %>
  <%=f.hidden_field :traveler_id%>
  Trip Name:
  <%= f.text_field :name %> </br>
  Trip Start Date: <%= f.datetime_select :start_date, :ampm => true, :start_year => 2018, :order => [:month, :day, :year] %></br>
  Trip End Date: <%= f.datetime_select :end_date, :ampm => true, :start_year => 2018, :order => [:month, :day, :year] %></br>
  <h3>What do you want to see?</h3>
  <h3><%=f.collection_check_boxes :attraction_ids, Attraction.all, :id, :name %></h3>
  <h3><a href="<%=new_attraction_path%>">Create New Attraction</a></h3>
  <%= f.submit %>
<%end%>

app/views/trips/edit.html.erb
<div class="row">
  <div class="column">
    <div class="info-text">
      <h1> Update Your Trip</h1> </br>
    </div>
  </div>
  <div class="column">
    <div class="form">
      <%= form_for @trip, url: traveler_trip_path(@trip.traveler, @trip), :method => :patch do |f| %>
      <% if @trip.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@trip.errors.count, "error") %>
            prohibited this post from being saved:
          <ul>
          <% @trip.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
          </h3>
        </div>
      <% end %>
        <%=f.hidden_field :traveler_id%>
        Trip Name:
        <%= f.text_field :name %> </br>
        Trip Start Date: <%= f.datetime_select :start_date, :ampm => true, :start_year => 2018, :order => [:month, :day, :year] %></br>
        Trip End Date: <%= f.datetime_select :end_date, :ampm => true, :start_year => 2018, :order => [:month, :day, :year] %></br>
        <h3>What do you want to see?</h3>
        <h3><%=f.collection_check_boxes :attraction_ids, Attraction.all, :id, :name %></h3>
        <h3><a href="<%=new_attraction_path%>">Create New Attraction</a></h3>
        <%= f.submit %>
      <%end%>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<div class="row">
  <div class="column">
    <div class="info-text">
      <h1> All <%=@traveler.name%>'s Trips</h1> </br>
    </div>
  </div>
  <div class="column">
    <div class="form">
      <% if @trips%>
        <%@trips.each do |trip|%>
          <%= link_to trip.name, traveler_trip_path(@traveler, trip)%> </br>
        <%end%>
      <%else%>
        <h2> You have no upcoming trips </h2>
      <%end%>
      </br><a href="<%= new_traveler_trip_path(@traveler)%>" class="button">Create New Trip</a>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<head>

</head>

<div class="row">
  <div class="column">
    <div class="info-text">
      <h1> Create Your Trip</h1> </br>
    </div>
  </div>
  <div class="column">
    <div class="form">
      <%= form_for @trip, url: traveler_trips_path do |f| %>
      <% if @trip.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@trip.errors.count, "error") %>
            prohibited this post from being saved:
          <ul>
          <% @trip.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
          </h3>
        </div>
      <% end %>
        <%=f.hidden_field :traveler_id%>
        Trip Name:
        <%= f.text_field :name %> </br>
        Trip Start Date: <%= f.datetime_select :start_date, :ampm => true, :start_year => 2018, :order => [:month, :day, :year] %></br>
        Trip End Date: <%= f.datetime_select :end_date, :ampm => true, :start_year => 2018, :order => [:month, :day, :year] %></br>
        <h3>What do you want to see?</h3>
        <h3 id="attraction_boxes"><%=f.collection_check_boxes :attraction_ids, Attraction.all, :id, :name %></h3>
        <%= f.submit %>
      <%end%>
      <h3><a id="createAttraction" href="#" >Create New Attraction</a></h3>
      <div id="createNewAttraction">
        <%=  form_for :attraction, url: attractions_path, html: {id:"new_attraction"} do |f| %>
          Name: <%=f.text_field :name %></br>
          Location: <%=f.text_field :location %></br>
          Hours: <%=f.text_field :hours %></br>
          Price: <%=f.text_field :price %></br>
        <%= f.submit %>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div class="row" >
  <div class="column">
    <div class="info-text">
      <h1><%=@trip.name%></h1>
    </div>
  </div>
  <div class="column">
    <div class="form">
      Dates: <%=@trip.start_date.strftime("%b %e, %Y")%> - <%=@trip.end_date.strftime("%b %e, %Y")%> </br>
      Planned Stops: </br>
      <%@trip.attractions.each do |attraction|%>
        <%=link_to attraction.name, attraction_path(attraction)%> </br>
      <%end%> </br>
      <%= link_to "Edit Trip", edit_traveler_trip_path(@trip.traveler, @trip) %>
    </div>
  </div>
<div>